kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: s2-l2-shared
  namespace: processing
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
  storageClassName: ceph-fs
