apiVersion: v1
kind: Secret
type: Opaque
data:
  mongo.password: "{{ mongodb.password | b64encode }}"
  mongo.username: "{{ mongodb.username | b64encode }}"
metadata:
  name: s2-l2-mongo
  namespace: processing

---

apiVersion: v1
kind: Secret
type: Opaque
data:
  obs.accessKey: "{{ s3.access_key | b64encode }}"
  obs.secretKey: "{{ s3.secret_key | b64encode }}"
metadata:
  name: s2-l2-obs
  namespace: processing
