---
  - name: "RPM deployed display"
    hosts: localhost
    connection: local 

    tasks:

    - name: "Checking list of today updated packages after L0_ install"
      shell: rpm -qa --last | grep "$(date +%a\ %d\ %b\ %Y)" |cut -f 1 -d " "
      register: result
      args:
        warn: no

    - name: "List of L0_ packages installed today"
      debug: msg="{{ result.stdout_lines }}"

    - name: "Checking list of S2IPF_ packages after L0_ install"
#      shell: rpm -qa 
      shell: rpm -qa  --last | grep "S2IPF_" |cut -f 1 -d " "
      register: result
      args:
        warn: no

    - name: "List of S2IPF_ packages installed"
      debug: msg="{{ result.stdout_lines }}"

