apiVersion: v1
kind: Secret
type: Opaque
data:
  mongo.password: "{{ mongodb.password }}"
  mongo.username: "{{ mongodb.username }}"
  obs.accessKey: "{{ obs.accessKey }}"
  obs.secretKey: "{{ obs.secretKey }}"
metadata:
  name: s2-l0c-pw
  namespace: processing

---

apiVersion: v1
kind: Secret
type: Opaque
data:
  obs.accessKey: "{{ obs.accessKey }}"
  obs.secretKey: "{{ obs.secretKey }}"
metadata:
  name: s2-l0c-ew
  namespace: processing

