apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: s2-l0c-job
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  partitions: 6
  replicas: 3
  config:
    retention.bytes: "-1"
    retention.ms: 259200000
    cleanup.policy: delete
    min.insync.replicas: 2
    unclean.leader.election.enable: false
