apiVersion: v1

kind: Secret

type: Opaque

data:
  mongo.password: "{{ mongodb.password }}"
  mongo.username: "{{ mongodb.username }}"
  obs.accessKey: "{{ obs.accessKey }}"
  obs.secretKey: "{{ obs.secretKey }}"

metadata:
  name: pw-l0u
  namespace: processing
