#### Setup

ARG JDK_URI=https://download.oracle.com/java/17/latest/jdk-17_linux-x64_bin.tar.gz

#### Fetch JDK

FROM ubuntu:focal AS jdk

RUN apt-get update \
    && apt-get install --no-install-recommends -y ca-certificates curl \
    && rm -rf /var/lib/apt/lists/*

ARG JDK_URI
RUN curl -L $JDK_URI > jdk.tar.gz

#### Build image from IPF

FROM artifactory.coprs.esa-copernicus.eu/s2-docker/s2level2:6.1.0

USER root

## Wrapper configuration
RUN groupadd -g 1000 wrapper \
    && adduser -p '*' -d /wrapper -u 1000 -g 1000 wrapper
COPY --from=jdk jdk.tar.gz /wrapper/jdk.tar.gz
RUN cd /wrapper \
    && tar xvf jdk.tar.gz \
    && mv jdk-* jdk \
    && rm jdk.tar.gz \
    && chown -R wrapper:wrapper /wrapper \
    && chmod -R 775 /wrapper

## Setup workspace folder
RUN mkdir -p /workspace \
    && chmod -R 775 /workspace \
    && chown -R wrapper:wrapper /workspace

## Setup SHARED folder (on shared volume)
RUN mkdir -p /shared  \
    && chmod -R 775 /shared  \
    && chown -R wrapper:wrapper /shared

## Orechestrator section

# Use UTC, not EST
RUN rm -f /etc/localtime  \
    && ln -s /usr/share/zoneinfo/UTC /etc/localtime

# Create orchestrator root
RUN mkdir -p /wrapper/orchestrator

# Add sources and deps
ADD inputs/orchestrator/deps.tgz /wrapper/orchestrator/
ADD inputs/l2/l2_scripts.tgz /wrapper/orchestrator/

# Configure and install
RUN rm -rf /usr/share/doc \
    && rpm -ivh /wrapper/orchestrator/dependencies_orchestrator/python-l*.rpm \
    && chown -R wrapper:wrapper /wrapper \
    && chown -R wrapper:wrapper /home/Sen2Cor-02.10.03-Linux64

# Add exiftool
RUN curl https://www.getpagespeed.com/files/centos6-eol.repo --output /etc/yum.repos.d/CentOS-Base.repo \
    && yum -y install perl \
    && yum -y install perl-devel \
    && cd /wrapper/orchestrator/dependencies_orchestrator \
    && tar -xzvf Image-ExifTool-12.50.tar.gz \
    && cd Image-ExifTool-12.50 \
    && perl Makefile.PL \
    && make test \
    && make install

WORKDIR /wrapper
USER wrapper
