#### Setup

ARG JDK_URI=https://download.oracle.com/java/17/latest/jdk-17_linux-x64_bin.tar.gz

#### Fetch JDK

FROM ubuntu:focal AS jdk

RUN apt-get update \
    && apt-get install --no-install-recommends -y ca-certificates curl \
    && rm -rf /var/lib/apt/lists/*

ARG JDK_URI
RUN curl -L $JDK_URI > jdk.tar.gz

#### Build image from IPF

FROM artifactory.coprs.esa-copernicus.eu/s2-docker/s2level0:5.1.0

USER root

## Wrapper configuration
RUN groupadd -g 1000 wrapper \
    && adduser -p '*' -d /wrapper -u 1000 -g 1000 wrapper
COPY --from=jdk jdk.tar.gz /wrapper/jdk.tar.gz
RUN cd /wrapper \
    && tar xvf jdk.tar.gz \
    && mv jdk-* jdk \
    && rm jdk.tar.gz \
    && chown -R wrapper:wrapper /wrapper \
    && chmod -R 775 /wrapper

## Setup workspace folder
RUN mkdir -p /workspace \
    && chmod -R 775 /workspace \
    && chown -R wrapper:wrapper /workspace

## Setup dhared folder (on shared volume)
RUN mkdir -p /shared \
    && chmod -R 775 /shared \
    && chown -R wrapper:wrapper /shared

WORKDIR /wrapper
USER wrapper
