#### Setup

ARG JDK_URI=https://download.java.net/java/GA/jdk17.0.2/dfd4a8d0985749f896bed50d7138ee7f/8/GPL/openjdk-17.0.2_linux-x64_bin.tar.gz
ARG JDK_VERSION=17.0.2

#### Fetch JDK

FROM ubuntu:focal AS jdk

RUN apt-get update \
    && apt-get install --no-install-recommends -y ca-certificates curl \
    && rm -rf /var/lib/apt/lists/*

ARG JDK_URI
RUN curl -L $JDK_URI > jdk.tar.gz

#### Build image from IPF

FROM artifactory.coprs.esa-copernicus.eu/s2-docker/s2level1:6.1.0

USER root

## Wrapper configuration
ARG JDK_VERSION
RUN groupadd -g 1001 wrapper  \
    && adduser -p '*' -d /wrapper -u 1001 -g 1001 wrapper  \
    && chmod 755 /wrapper
COPY --from=jdk jdk.tar.gz /wrapper/jdk.tar.gz
RUN cd /wrapper \
    && tar xvf jdk.tar.gz \
    && mv jdk-$JDK_VERSION jdk \
    && rm jdk.tar.gz \
    && chown -R wrapper:wrapper /wrapper

## Setup workspace folder
RUN mkdir -p /workspace \
    && chmod -R 755 /workspace \
    && chown -R wrapper:wrapper /workspace

## Setup SHARED folder (on shared volume)
RUN mkdir -p /shared  \
    && chmod -R 755 /shared  \
    && chown -R wrapper:wrapper /shared

## Orechestrator section

# Use UTC, not EST
RUN rm -f /etc/localtime  \
    && ln -s /usr/share/zoneinfo/UTC /etc/localtime

# Create orchestrator root
RUN mkdir -p /wrapper/orchestrator

# Add sources and deps
ADD orchestrator/deps.tgz /wrapper/orchestrator/
ADD orchestrator/orchestrator.tgz /wrapper/orchestrator/
ADD orchestrator/rs_scripts.tgz /wrapper/orchestrator/

# Configure and install
RUN rm -rf /usr/share/doc \
    && rpm -ivh /wrapper/orchestrator/dependencies_orchestrator/python-*.rpm \
    && cd /wrapper/orchestrator/S2IPF_Orchestrator  \
    && touch README \
    && python setup.py install \
    && chown -R wrapper:wrapper /wrapper

WORKDIR /wrapper
USER wrapper
