logging:
  level:
    com:
      amazonaws: INFO
    eu:
      csgroup:
        coprs: INFO

spring:
  application:
    name: stub-rmg
  cloud:
    stream:
      function:
        bindings:
          supply-out-0: output
