name: PS2 Docker build (releases)

on:
  push:
    branches:
      - 'main'
      - 'release/**'
    tags:
      - "[0-9]+.[0-9]+.[0-9]+-rc[0-9]+"
      - "[0-9]+.[0-9]+.[0-9]"
  workflow_dispatch: { }

env:
  REGISTRY_USER: ${{ secrets.ARTIFACTORY_USER }}
  REGISTRY_PWD: ${{ secrets.ARTIFACTORY_PASSWORD }}
  REGISTRY_BASE: artifactory.coprs.esa-copernicus.eu
  REGISTRY_PROJECT: rs-docker-private
  SONARQUBE_HOST: ${{ secrets.SONARQUBE_HOST }}
  SONARQUBE_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
  SCAN_SEVERITY: 'CRITICAL,HIGH'
  SCAN_EXIT_CODE: '0'

jobs:

  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        component: [pw-l0u, pw-l0c, pw-l1s, pw-l1c, pw-l2, ew-l0u, ew-l0c, ew-l1sa, ew-l1sb, ew-l1ab, ew-l1c, ew-l2-ds, ew-l2-tl]

    steps:

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # fetch all history so multiple commits can be scanned

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up environment
        run: |
          # Sonar
          echo "SONARQUBE_HOST=${{ env.SONARQUBE_HOST }}" >> $GITHUB_ENV
          echo "SONARQUBE_TOKEN=${{ env.SONARQUBE_TOKEN }}" >> $GITHUB_ENV

          # Git
          GIT_BRANCH=${{ github.ref_name }}
          echo "GIT_BRANCH=$GIT_BRANCH" >> $GITHUB_ENV
          echo Building branch : $GIT_BRANCH

          # Set version for docker tasks
          echo "BUILD_VERSION=$(grep  "version = " apps/build.gradle | cut -d"'" -f 2)" >> $GITHUB_ENV

      - name: Log into registry ${{ env.REGISTRY_BASE }}/${{ env.REGISTRY_PROJECT }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY_BASE }}/${{ env.REGISTRY_PROJECT }}
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PWD }}

      - name: Build base docker images l0u
        if: contains(matrix.component, 'l0u')
        run: |
          docker build . -f apps/execution/docker/Dockerfile_s2-ipf-l0u-jdk17 -t s2-ipf-l0u-jdk17

      - name: Build base docker images l0c
        if: contains(matrix.component, 'l0c')
        run: |
          docker build . -f apps/execution/docker/Dockerfile_s2level0-jdk17 -t s2level0-jdk17

      - name: Build base docker images l1
        if: contains(matrix.component, 'l1')
        run: |
          docker build . -f apps/execution/docker/Dockerfile_s2level1-jdk17 -t s2level1-jdk17

      - name: Build base docker images l2
        if: contains(matrix.component, 'l2')
        run: |
          docker build . -f apps/execution/docker/Dockerfile_s2level2-jdk17 -t s2level2-jdk17

      - name: Build with Gradle preparation
        if: startsWith(matrix.component, 'pw')
        uses: gradle/gradle-build-action@v2
        with:
          arguments: clean apps:preparation:${{ matrix.component }}:build apps:preparation:${{ matrix.component }}:bootBuildImage

      - name: Build with Gradle execution
        if: startsWith(matrix.component, 'ew')
        uses: gradle/gradle-build-action@v2
        with:
          arguments: clean apps:execution:${{ matrix.component }}:build apps:execution:${{ matrix.component }}:bootBuildImage apps:execution:${{ matrix.component }}:docker

      - name: Remove base docker images
        run: |
          docker rmi s2level0-jdk17 s2-ipf-l0u-jdk17 s2level1-jdk17 s2level2-jdk17 --force

      - name: Docker security scan
        uses: COPRS/reference-system-software@trivy-security-scan-v1
        with:
          IMAGE_REF: ${{ env.REGISTRY_BASE }}/${{ env.REGISTRY_PROJECT }}/${{ matrix.component }}:${{ env.BUILD_VERSION }}
          ARTIFACT_NAME: ${{ matrix.component }}_${{ env.BUILD_VERSION }}
          EXIT_CODE: ${{ env.SCAN_EXIT_CODE }}
          SEVERITY: ${{ env.SCAN_SEVERITY }}

      - name: Push and clean docker image
        run: |
          docker image push ${{ env.REGISTRY_BASE }}/${{ env.REGISTRY_PROJECT }}/${{ matrix.component }}:${{ env.BUILD_VERSION }}
          docker rmi -f ${{ env.REGISTRY_BASE }}/${{ env.REGISTRY_PROJECT }}/${{ matrix.component }}:${{ env.BUILD_VERSION }}

  sonar:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # fetch all history so multiple commits can be scanned

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up environment
        run: |
          # Sonar
          echo "SONARQUBE_HOST=${{ env.SONARQUBE_HOST }}" >> $GITHUB_ENV
          echo "SONARQUBE_TOKEN=${{ env.SONARQUBE_TOKEN }}" >> $GITHUB_ENV

          # Git
          GIT_BRANCH=${{ github.ref_name }}
          echo "GIT_BRANCH=$GIT_BRANCH" >> $GITHUB_ENV
          echo Building branch : $GIT_BRANCH

          # Set version for docker tasks
          echo "BUILD_VERSION=$(grep  "version = " apps/build.gradle | cut -d"'" -f 2)" >> $GITHUB_ENV

      - name: Build with Gradle execution
        uses: gradle/gradle-build-action@v2
        with:
          arguments: clean build sonar
