name: PS2 Docker build

on:
  push:
    branches:
      - 'develop'
      - 'main'
      - 'release/**'
      - 'feature/**'
      - 'fix/**'
    tags:
      - "[0-9]+.[0-9]+.[0-9]+-rc[0-9]+"
      - "[0-9]+.[0-9]+.[0-9]"
  workflow_dispatch: { }

env:
  REGISTRY_USER: ${{ secrets.ARTIFACTORY_USER }}
  REGISTRY_PWD: ${{ secrets.ARTIFACTORY_PASSWORD }}
  REGISTRY_BASE: artifactory.coprs.esa-copernicus.eu
  REGISTRY_PROJECT: rs-docker-private
  REGISTRY_FOLDER: ""
  SONARQUBE_HOST: ${{ secrets.SONARQUBE_HOST }}
  SONARQUBE_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
  BRANCH_REGEX: "^(main$|release/*)"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # fetch all history so multiple commits can be scanned

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up environment
        run: |
          
          # Artifactory
          echo "REGISTRY_USER=${{ env.REGISTRY_USER }}" >> $GITHUB_ENV
          echo "REGISTRY_PWD=${{ env.REGISTRY_PWD }}" >> $GITHUB_ENV
          echo "REGISTRY_BASE=${{ env.REGISTRY_BASE }}" >> $GITHUB_ENV
          echo "REGISTRY_PROJECT=${{ env.REGISTRY_PROJECT }}" >> $GITHUB_ENV
          echo "REGISTRY_FOLDER=${{ env.REGISTRY_FOLDER }}" >> $GITHUB_ENV
          
          # Sonar
          echo "SONARQUBE_HOST=${{ env.SONARQUBE_HOST }}" >> $GITHUB_ENV
          echo "SONARQUBE_TOKEN=${{ env.SONARQUBE_TOKEN }}" >> $GITHUB_ENV
          
          # Git
          GIT_BRANCH=${{ github.ref_name }}
          echo "GIT_BRANCH=$GIT_BRANCH" >> $GITHUB_ENV
          echo Building branch : $GIT_BRANCH
          
          # Set project version for work branches
          if ! [[ $GIT_BRANCH =~ ${{ env.BRANCH_REGEX }} ]]; then
            BRANCH_NAME=$(echo $GIT_BRANCH | sed s:/:_:g)
            echo Setting project version : $BRANCH_NAME
            sed -i -E "s/(version = ').*(')/\1$BRANCH_NAME\2/" apps/build.gradle
          fi

      - name: Log into registry ${{ env.REGISTRY_BASE }}/${{ env.REGISTRY_PROJECT }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY_BASE }}/${{ env.REGISTRY_PROJECT }}
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PWD }}

      - name: Build base docker images
        run: |
          docker build . -f apps/execution/docker/Dockerfile_s2-ipf-l0u-jdk17 -t s2-ipf-l0u-jdk17
          docker build . -f apps/execution/docker/Dockerfile_s2level0-jdk17 -t s2level0-jdk17
          docker build . -f apps/execution/docker/Dockerfile_s2level1-jdk17 -t s2level1-jdk17
          docker build . -f apps/execution/docker/Dockerfile_s2level2-jdk17 -t s2level2-jdk17

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: clean build sonar bootBuildImage docker dockerPush
